Repository TeamPophory/pophory-server, pull requests merged in 2023-07, with the labels that each got.

#22 [feat #3] jwt setting
  build.gradle
  src/main/java/com/pophory/pophoryserver/global/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/pophory/pophoryserver/global/config/jwt/JwtTokenProvider.java
  src/main/java/com/pophory/pophoryserver/global/config/jwt/JwtValidationType.java
  src/main/java/com/pophory/pophoryserver/global/config/jwt/UserAuthentication.java
Labels: ⚙️SETTING, 🌱YUNDOL

#19 [feat #16] 사진 삭제 API 구현
  src/main/java/com/pophory/pophoryserver/domain/photo/Photo.java
  src/main/java/com/pophory/pophoryserver/domain/photo/PhotoController.java
  src/main/java/com/pophory/pophoryserver/domain/photo/PhotoService.java
Labels: ✨FEAT, 🚀API

#24 [feat #18] 앨범 목록 조회, 앨범 내 사진 목록 조회 API 구현
  src/main/java/com/pophory/pophoryserver/domain/album/Album.java
  src/main/java/com/pophory/pophoryserver/domain/album/AlbumController.java
  src/main/java/com/pophory/pophoryserver/domain/album/AlbumJpaRepository.java
  src/main/java/com/pophory/pophoryserver/domain/album/AlbumService.java
  src/main/java/com/pophory/pophoryserver/domain/album/dto/response/AlbumGetResponseDto.java
  src/main/java/com/pophory/pophoryserver/domain/album/dto/response/AlbumListGetResponseDto.java
  src/main/java/com/pophory/pophoryserver/domain/photo/Photo.java
  src/main/java/com/pophory/pophoryserver/domain/photo/PhotoController.java
  src/main/java/com/pophory/pophoryserver/domain/photo/PhotoJpaRepository.java
  src/main/java/com/pophory/pophoryserver/domain/photo/PhotoService.java
  src/main/java/com/pophory/pophoryserver/domain/photo/dto/request/PhotoAddRequestDto.java
  src/main/java/com/pophory/pophoryserver/domain/photo/dto/response/PhotoGetResponseDto.java
  src/main/java/com/pophory/pophoryserver/domain/photo/dto/response/PhotoListGetResponseDto.java
  src/main/java/com/pophory/pophoryserver/global/util/PhotoUtil.java
Labels: 🚀API, 🐻UNAN

#27 [feat #23] 마이페이지 조회 API 구현
  src/main/java/com/pophory/pophoryserver/domain/member/MemberController.java
  src/main/java/com/pophory/pophoryserver/domain/member/MemberService.java
  src/main/java/com/pophory/pophoryserver/domain/member/dto/request/MemberCreateRequestDto.java
  src/main/java/com/pophory/pophoryserver/domain/member/dto/response/MemberMyPageGetResponseDto.java
  src/main/java/com/pophory/pophoryserver/domain/photo/dto/response/PhotoGetResponseDto.java
  src/main/java/com/pophory/pophoryserver/global/utils/PhotoUtil.java
Labels: 🚀API, 🌱YUNDOL

#30 [chore #29] utils package 정리
  src/main/java/com/pophory/pophoryserver/domain/photo/dto/response/PhotoGetResponseDto.java
  src/main/java/com/pophory/pophoryserver/global/utils/PhotoUtil.java
Labels: 🐻UNAN

#33 [setting #5] Swagger 설정 및 적용
  build.gradle
  src/main/java/com/pophory/pophoryserver/HealthCheckController.java
  src/main/java/com/pophory/pophoryserver/TestController.java
  src/main/java/com/pophory/pophoryserver/domain/album/AlbumController.java
  src/main/java/com/pophory/pophoryserver/domain/member/MemberController.java
  src/main/java/com/pophory/pophoryserver/domain/member/auth/AuthController.java
  src/main/java/com/pophory/pophoryserver/domain/member/dto/request/MemberCreateRequestDto.java
  src/main/java/com/pophory/pophoryserver/domain/photo/PhotoController.java
  src/main/java/com/pophory/pophoryserver/domain/photo/dto/PhotoAddRequestDto.java
  src/main/java/com/pophory/pophoryserver/domain/photo/dto/request/PhotoAddRequestDto.java
  src/main/java/com/pophory/pophoryserver/domain/studio/StudioController.java
  src/main/java/com/pophory/pophoryserver/global/config/SwaggerConfig.java
Labels: ⚙️SETTING, 🐻UNAN

#36 [refactor #31] 사진 API 개선 및 Swagger 추가 적용
  src/main/java/com/pophory/pophoryserver/domain/album/AlbumController.java
  src/main/java/com/pophory/pophoryserver/domain/album/dto/response/AlbumGetResponseDto.java
  src/main/java/com/pophory/pophoryserver/domain/album/dto/response/AlbumListGetResponseDto.java
  src/main/java/com/pophory/pophoryserver/domain/member/MemberController.java
  src/main/java/com/pophory/pophoryserver/domain/member/dto/response/MemberGetResponseDto.java
  src/main/java/com/pophory/pophoryserver/domain/member/dto/response/MemberMyPageGetResponseDto.java
  src/main/java/com/pophory/pophoryserver/domain/photo/Photo.java
  src/main/java/com/pophory/pophoryserver/domain/photo/PhotoController.java
  src/main/java/com/pophory/pophoryserver/domain/photo/PhotoService.java
  src/main/java/com/pophory/pophoryserver/domain/photo/dto/response/PhotoGetResponseDto.java
  src/main/java/com/pophory/pophoryserver/domain/photo/dto/response/PhotoListGetResponseDto.java
  src/main/java/com/pophory/pophoryserver/domain/photo/vo/PhotoSizeVO.java
  src/main/java/com/pophory/pophoryserver/domain/studio/StudioController.java
Labels: 🚀API, 🐻UNAN

#41 [refactor #28] security 설정 변경 및 authentication 적용
  src/main/java/com/pophory/pophoryserver/domain/album/AlbumController.java
  src/main/java/com/pophory/pophoryserver/domain/member/Member.java
  src/main/java/com/pophory/pophoryserver/domain/member/MemberController.java
  src/main/java/com/pophory/pophoryserver/domain/member/auth/AppleAuthService.java
  src/main/java/com/pophory/pophoryserver/domain/member/auth/AuthService.java
  src/main/java/com/pophory/pophoryserver/domain/member/auth/KakaoAuthService.java
  src/main/java/com/pophory/pophoryserver/domain/member/auth/SocialService.java
  src/main/java/com/pophory/pophoryserver/domain/member/auth/dto/response/AuthResponseDto.java
  src/main/java/com/pophory/pophoryserver/domain/photo/PhotoController.java
  src/main/java/com/pophory/pophoryserver/domain/studio/StudioController.java
  src/main/java/com/pophory/pophoryserver/global/config/SecurityConfig.java
  src/main/java/com/pophory/pophoryserver/global/config/jwt/CustomJwtAuthenticationEntryPoint.java
  src/main/java/com/pophory/pophoryserver/global/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/pophory/pophoryserver/global/config/jwt/JwtTokenProvider.java
  src/main/java/com/pophory/pophoryserver/global/util/MemberUtil.java
Labels: 🚀API, 🐞BUG, 🐻UNAN

#48 [refactor #44] 회원정보 등록 API 수정
  src/main/java/com/pophory/pophoryserver/domain/album/Album.java
  src/main/java/com/pophory/pophoryserver/domain/album/AlbumJpaRepository.java
  src/main/java/com/pophory/pophoryserver/domain/member/MemberService.java
  src/main/java/com/pophory/pophoryserver/global/advice/ControllerExceptionHandler.java
Labels: 🚀API, 🐞BUG, 🌱YUNDOL

#52 [refactor #37] 배포를 위한 설정 변경
  build.gradle
  scripts/deploy.sh
  src/main/java/com/pophory/pophoryserver/domain/member/auth/AuthService.java
  src/main/java/com/pophory/pophoryserver/domain/photo/PhotoService.java
  src/main/java/com/pophory/pophoryserver/infrastructure/s3/S3Util.java
Labels: 🚀API, 🐻UNAN

#57 [Feat] #54 - nickname 중복체크 API 구현
  src/main/java/com/pophory/pophoryserver/domain/member/MemberController.java
  src/main/java/com/pophory/pophoryserver/domain/member/MemberService.java
  src/main/java/com/pophory/pophoryserver/domain/member/dto/request/MemberNicknameDuplicateRequestDto.java
  src/main/java/com/pophory/pophoryserver/domain/member/dto/response/MemberNicknameDuplicateResponseDto.java
Labels: 🚀API, 🌱YUNDOL

#56 [Fix] #55 - 사진추가 API 수정 및 소셜로그인 Response Dto명 변경
  src/main/java/com/pophory/pophoryserver/domain/member/auth/dto/response/AuthResponseDto.java
  src/main/java/com/pophory/pophoryserver/domain/photo/Photo.java
  src/main/java/com/pophory/pophoryserver/domain/photo/PhotoService.java
  src/main/java/com/pophory/pophoryserver/domain/photo/dto/response/PhotoGetResponseDto.java
Labels: 🐞BUG, 🌱YUNDOL

#66 [docs #32] README.md 작성
  README.md
Labels: 📔DOCS, 🌱YUNDOL

#62 [fix #59] 소셜로그인 isRegistered 기준 변경
  src/main/java/com/pophory/pophoryserver/domain/album/Album.java
  src/main/java/com/pophory/pophoryserver/domain/member/Member.java
  src/main/java/com/pophory/pophoryserver/domain/member/auth/SocialService.java
  src/main/java/com/pophory/pophoryserver/domain/photo/Photo.java
  src/main/java/com/pophory/pophoryserver/global/advice/ControllerExceptionHandler.java
Labels: 🚀API, 🐻UNAN

#69 [setting #38] querydsl 세팅
  build.gradle
  src/main/java/com/pophory/pophoryserver/global/config/JpaQueryFactoryConfig.java
Labels: ⚙️SETTING, 🐻UNAN

#75 [feat #70] test 푸쉬 알림 API 구현
  .github/workflows/ci.yml
  .gitignore
  build.gradle
  src/main/java/com/pophory/pophoryserver/domain/fcm/FcmController.java
  src/main/java/com/pophory/pophoryserver/domain/fcm/FcmService.java
  src/main/java/com/pophory/pophoryserver/domain/fcm/dto/FcmDto.java
  src/main/java/com/pophory/pophoryserver/domain/fcm/dto/MessageDto.java
  src/main/java/com/pophory/pophoryserver/domain/fcm/dto/NotificationDto.java
  src/main/java/com/pophory/pophoryserver/domain/fcm/dto/request/FcmRequestDto.java
  src/main/java/com/pophory/pophoryserver/global/advice/ControllerExceptionHandler.java
  src/main/java/com/pophory/pophoryserver/global/config/SecurityConfig.java
Labels: 🚀API, 🐻UNAN

#73 [fix #71] 토큰 재발급 API Swagger 수정
  src/main/java/com/pophory/pophoryserver/domain/auth/AppleAuthService.java
  src/main/java/com/pophory/pophoryserver/domain/auth/AuthController.java
  src/main/java/com/pophory/pophoryserver/domain/auth/AuthService.java
  src/main/java/com/pophory/pophoryserver/domain/auth/KakaoAuthService.java
  src/main/java/com/pophory/pophoryserver/domain/auth/SocialService.java
  src/main/java/com/pophory/pophoryserver/domain/auth/SocialType.java
  src/main/java/com/pophory/pophoryserver/domain/auth/dto/TokenVO.java
  src/main/java/com/pophory/pophoryserver/domain/auth/dto/request/AuthRequestDto.java
  src/main/java/com/pophory/pophoryserver/domain/auth/dto/response/AuthResponseDto.java
  src/main/java/com/pophory/pophoryserver/domain/auth/dto/response/TokenResponseDto.java
  src/main/java/com/pophory/pophoryserver/domain/member/Member.java
  src/main/java/com/pophory/pophoryserver/domain/member/MemberJpaRepository.java
  src/main/java/com/pophory/pophoryserver/domain/member/auth/SocialType.java
Labels: 🚀API, 🐻UNAN

#74 [chore #72] 패키지 변경 및 스웨거 문서 정리
  src/main/java/com/pophory/pophoryserver/HealthCheckController.java
  src/main/java/com/pophory/pophoryserver/TestController.java
  src/main/java/com/pophory/pophoryserver/domain/album/AlbumController.java
  src/main/java/com/pophory/pophoryserver/domain/auth/dto/response/TokenResponseDto.java
  src/main/java/com/pophory/pophoryserver/domain/member/MemberController.java
  src/main/java/com/pophory/pophoryserver/domain/photo/PhotoController.java
  src/main/java/com/pophory/pophoryserver/domain/photo/PhotoService.java
  src/main/java/com/pophory/pophoryserver/domain/s3/S3Service.java
  src/main/java/com/pophory/pophoryserver/domain/studio/StudioController.java
  src/main/java/com/pophory/pophoryserver/global/config/AwsS3Config.java
  src/main/java/com/pophory/pophoryserver/global/config/jwt/JwtAuthenticationFilter.java
Labels: ✂️CHORE, 🐻UNAN

#78 [chore #76] v1, v2 파일 분리 및 Tag 수정
  src/main/java/com/pophory/pophoryserver/domain/album/controller/AlbumV1Controller.java
  src/main/java/com/pophory/pophoryserver/domain/album/controller/AlbumV2Controller.java
  src/main/java/com/pophory/pophoryserver/domain/auth/controller/AuthV1Controller.java
  src/main/java/com/pophory/pophoryserver/domain/auth/controller/AuthV2Controller.java
  src/main/java/com/pophory/pophoryserver/domain/member/controller/MemberV1Controller.java
  src/main/java/com/pophory/pophoryserver/domain/member/controller/MemberV2Controller.java
  src/main/java/com/pophory/pophoryserver/domain/photo/controller/PhotoV1Controller.java
  src/main/java/com/pophory/pophoryserver/domain/photo/controller/PhotoV2Controller.java
  src/main/java/com/pophory/pophoryserver/domain/studio/controller/StudioV1Controller.java
  src/main/java/com/pophory/pophoryserver/domain/studio/controller/StudioV2Controller.java
Labels: ✂️CHORE, 🌱YUNDOL

#80 [chore #79] code 정리
  build.gradle
  src/main/java/com/pophory/pophoryserver/domain/album/Album.java
  src/main/java/com/pophory/pophoryserver/domain/album/AlbumJpaRepository.java
  src/main/java/com/pophory/pophoryserver/domain/album/controller/AlbumV1Controller.java
  src/main/java/com/pophory/pophoryserver/domain/album/dto/response/AlbumGetResponseDto.java
  src/main/java/com/pophory/pophoryserver/domain/album/dto/response/AlbumListGetResponseDto.java
  src/main/java/com/pophory/pophoryserver/domain/auth/controller/AuthV1Controller.java
  src/main/java/com/pophory/pophoryserver/domain/fcm/FcmService.java
  src/main/java/com/pophory/pophoryserver/domain/member/MemberJpaRepository.java
  src/main/java/com/pophory/pophoryserver/domain/member/controller/MemberV1Controller.java
  src/main/java/com/pophory/pophoryserver/domain/photo/PhotoService.java
  src/main/java/com/pophory/pophoryserver/domain/studio/dto/StudioResponseDto.java
  src/main/java/com/pophory/pophoryserver/global/config/JpaAuditingConfig.java
  src/main/java/com/pophory/pophoryserver/global/config/JpaQueryFactoryConfig.java
  src/main/java/com/pophory/pophoryserver/global/config/SwaggerConfig.java
  src/main/java/com/pophory/pophoryserver/global/config/TimeZoneConfig.java
  src/main/java/com/pophory/pophoryserver/global/util/PhotoUtil.java
Labels: ✂️CHORE, 🐻UNAN

#82 [feat #81] S3 presigned url 제공 api, 사진 upload api 개발
  src/main/java/com/pophory/pophoryserver/domain/album/Album.java
  src/main/java/com/pophory/pophoryserver/domain/fcm/FcmController.java
  src/main/java/com/pophory/pophoryserver/domain/member/Member.java
  src/main/java/com/pophory/pophoryserver/domain/member/MemberService.java
  src/main/java/com/pophory/pophoryserver/domain/photo/Photo.java
  src/main/java/com/pophory/pophoryserver/domain/photo/PhotoService.java
  src/main/java/com/pophory/pophoryserver/domain/photo/controller/PhotoV1Controller.java
  src/main/java/com/pophory/pophoryserver/domain/photo/controller/PhotoV2Controller.java
  src/main/java/com/pophory/pophoryserver/domain/photo/dto/request/PhotoAddV1RequestDto.java
  src/main/java/com/pophory/pophoryserver/domain/photo/dto/request/PhotoAddV2RequestDto.java
  src/main/java/com/pophory/pophoryserver/domain/photo/dto/response/PhotoAddResponseDto.java
  src/main/java/com/pophory/pophoryserver/domain/photo/vo/PhotoSizeVO.java
  src/main/java/com/pophory/pophoryserver/domain/s3/S3Controller.java
  src/main/java/com/pophory/pophoryserver/domain/s3/S3Service.java
  src/main/java/com/pophory/pophoryserver/domain/s3/UploadType.java
  src/main/java/com/pophory/pophoryserver/domain/s3/dto/response/S3GetPresignedUrlResponseDto.java
  src/main/java/com/pophory/pophoryserver/global/util/MemberUtil.java
  src/main/java/com/pophory/pophoryserver/global/util/PhotoUtil.java
Labels: 🚀API, 🐻UNAN

#86 [docs #84] README에 서비스 이미지 추가
  README.md
Labels: 📔DOCS, 🌱YUNDOL

#94 [feat #93] 사진 삭제 API V2 구현
  src/main/java/com/pophory/pophoryserver/domain/photo/controller/PhotoV2Controller.java
Labels: 🚀API, 🐻UNAN

#90 [feat #87] 앨범 목록 조회 V2 구현
  src/main/java/com/pophory/pophoryserver/domain/album/controller/AlbumV2Controller.java
Labels: 🚀API, 🐻UNAN

#89 [feat #85] 마이페이지 조회 API 구현 V2 개발
  src/main/java/com/pophory/pophoryserver/domain/member/MemberService.java
  src/main/java/com/pophory/pophoryserver/domain/member/controller/MemberV2Controller.java
  src/main/java/com/pophory/pophoryserver/domain/member/dto/response/MemberMyPageGetV2ResponseDto.java
Labels: 🚀API, 🌱YUNDOL

#99 [fix #98] 사용자 정보 조회 API 수정
  src/main/java/com/pophory/pophoryserver/domain/member/controller/MemberV2Controller.java
  src/main/java/com/pophory/pophoryserver/domain/member/dto/response/MemberGetResponseDto.java
Labels: 🚀API, 🐞BUG, 🐻UNAN

#102 [feat #95] 앨범 단건 조회 API 개발
  src/main/java/com/pophory/pophoryserver/domain/album/AlbumService.java
  src/main/java/com/pophory/pophoryserver/domain/album/controller/AlbumV2Controller.java
Labels: 🚀API, 🐻UNAN

#106 [feat #104] 앨범 내 사진 목록 조회 API V2 개발
  src/main/java/com/pophory/pophoryserver/domain/album/controller/AlbumV2Controller.java
  src/main/java/com/pophory/pophoryserver/domain/auth/SocialService.java
Labels: 🚀API, 🐻UNAN

#107 [feat #100] 소셜로그인 API V2 개발
  src/main/java/com/pophory/pophoryserver/domain/auth/controller/AuthV2Controller.java
  src/main/java/com/pophory/pophoryserver/global/config/SecurityConfig.java
Labels: 🚀API, 🌱YUNDOL

#108 [feat #101] 멤버 아이디 중복체크 API V2 개발
  src/main/java/com/pophory/pophoryserver/domain/member/controller/MemberV2Controller.java
Labels: 🚀API, 🌱YUNDOL

#117 [feat #111] 사진관 목록 전체 조회 API V2 개발
  src/main/java/com/pophory/pophoryserver/domain/studio/StudioService.java
  src/main/java/com/pophory/pophoryserver/domain/studio/controller/StudioV2Controller.java
  src/main/java/com/pophory/pophoryserver/domain/studio/dto/StudioGetResponseDto.java
  src/main/java/com/pophory/pophoryserver/domain/studio/dto/StudioResponseDto.java
  src/main/java/com/pophory/pophoryserver/domain/studio/dto/StudioV2ResponseDto.java
Labels: 🚀API, 🌱YUNDOL

#123 [feat #120] Version 관련 API 구현
  src/main/java/com/pophory/pophoryserver/domain/version/OSType.java
  src/main/java/com/pophory/pophoryserver/domain/version/ServiceVersion.java
  src/main/java/com/pophory/pophoryserver/domain/version/ServiceVersionController.java
  src/main/java/com/pophory/pophoryserver/domain/version/ServiceVersionJpaRepository.java
  src/main/java/com/pophory/pophoryserver/domain/version/ServiceVersionService.java
  src/main/java/com/pophory/pophoryserver/domain/version/dto/VersionGetResponseDto.java
  src/main/java/com/pophory/pophoryserver/domain/version/dto/VersionListGetResponseDto.java
  src/main/java/com/pophory/pophoryserver/domain/version/dto/VersionUpdateRequestDto.java
  src/main/java/com/pophory/pophoryserver/global/config/SecurityConfig.java
Labels: ✨FEAT, 🚀API, 🐻UNAN

#127 [fix #126] 사진관 선택하지 않을 시 response값 NONE으로 변경
  src/main/java/com/pophory/pophoryserver/domain/photo/dto/response/PhotoGetResponseDto.java
  src/main/java/com/pophory/pophoryserver/domain/photo/dto/response/PhotoGetV2ResponseDto.java
Labels: 🐞BUG, 🌱YUNDOL

#130 [hotfix #129] 앨범 로직 수정
  src/main/java/com/pophory/pophoryserver/domain/album/Album.java
  src/main/java/com/pophory/pophoryserver/domain/album/dto/response/AlbumGetResponseDto.java
  src/main/java/com/pophory/pophoryserver/domain/album/dto/response/AlbumGetV2ResponseDto.java
  src/main/java/com/pophory/pophoryserver/domain/albumtheme/AlbumDesign.java
  src/main/java/com/pophory/pophoryserver/domain/member/MemberService.java
  src/main/java/com/pophory/pophoryserver/domain/member/dto/request/MemberCreateRequestDto.java
  src/main/java/com/pophory/pophoryserver/domain/member/dto/request/MemberCreateV2RequestDto.java
  src/main/java/com/pophory/pophoryserver/global/config/SecurityConfig.java
Labels: 🔥HOTFIX, 🌱YUNDOL

#135 [fix #134] 사진 전체 조회 response에 sharedId 추가
  src/main/java/com/pophory/pophoryserver/domain/photo/dto/response/PhotoAllListV2ResponseDto.java
  src/main/java/com/pophory/pophoryserver/domain/photo/service/PhotoService.java
Labels: 🐞BUG, 🌱YUNDOL

#131 [feat #97] 앨범 디자인 수정 API V2 개발
  src/main/java/com/pophory/pophoryserver/domain/album/AlbumService.java
  src/main/java/com/pophory/pophoryserver/domain/album/controller/AlbumV2Controller.java
  src/main/java/com/pophory/pophoryserver/domain/album/dto/request/AlbumDesignUpdateRequestDto.java
  src/main/java/com/pophory/pophoryserver/domain/version/ServiceVersion.java
Labels: 🚀API, 🌱YUNDOL

#137 [feat #136] album design 정보 조회 API 개발
  src/main/java/com/pophory/pophoryserver/domain/albumtheme/AlbumCover.java
  src/main/java/com/pophory/pophoryserver/domain/albumtheme/AlbumDesignController.java
  src/main/java/com/pophory/pophoryserver/domain/albumtheme/AlbumDesignService.java
  src/main/java/com/pophory/pophoryserver/domain/albumtheme/AlbumTheme.java
  src/main/java/com/pophory/pophoryserver/domain/albumtheme/dto/response/AlbumDesignGetResponseDto.java
  src/main/java/com/pophory/pophoryserver/domain/albumtheme/dto/response/AlbumDesignListGetResponseDto.java
  src/main/java/com/pophory/pophoryserver/domain/photo/controller/PhotoV1Controller.java
  src/main/java/com/pophory/pophoryserver/domain/photo/controller/PhotoV2Controller.java
  src/main/java/com/pophory/pophoryserver/domain/s3/S3Controller.java
  src/main/java/com/pophory/pophoryserver/global/config/SecurityConfig.java
Labels: 🚀API, 🐻UNAN

#139 [fix #124] swagger 문서 편집
  src/main/java/com/pophory/pophoryserver/domain/album/controller/AlbumV2Controller.java
  src/main/java/com/pophory/pophoryserver/domain/album/dto/request/AlbumDesignUpdateRequestDto.java
Labels: ✂️CHORE, 🌱YUNDOL

#141 [fix #138] requestDto 수정
  src/main/java/com/pophory/pophoryserver/domain/album/AlbumService.java
  src/main/java/com/pophory/pophoryserver/domain/album/dto/request/AlbumDesignUpdateRequestDto.java
Labels: ✂️CHORE, 🌱YUNDOL

#143 [fix #142] 앨범 내 사진 조회 최신순으로 정렬
  src/main/java/com/pophory/pophoryserver/domain/album/AlbumService.java
Labels: ✂️CHORE, 🌱YUNDOL

#144 [fix #140] 앨범 공유 수락 API 로직 수정
  src/main/java/com/pophory/pophoryserver/domain/auth/SocialService.java
  src/main/java/com/pophory/pophoryserver/domain/auth/SocialType.java
  src/main/java/com/pophory/pophoryserver/domain/auth/controller/AuthV2Controller.java
  src/main/java/com/pophory/pophoryserver/domain/photo/controller/PhotoShareController.java
  src/main/java/com/pophory/pophoryserver/domain/photo/service/PhotoShareService.java
  src/main/java/com/pophory/pophoryserver/global/advice/ControllerExceptionHandler.java
  src/main/java/com/pophory/pophoryserver/global/exception/SelfApproveException.java
  src/main/java/com/pophory/pophoryserver/global/response/ResponseCode.java
Labels: 🚀API, 🐞BUG, 🐻UNAN

#146 [feat #128] 포토부스 관련 API 구현
  src/main/java/com/pophory/pophoryserver/domain/member/MemberJpaRepository.java
  src/main/java/com/pophory/pophoryserver/domain/photo/dto/request/PhotoAddV2RequestDto.java
  src/main/java/com/pophory/pophoryserver/domain/photo/dto/request/PhotoShareRequestDto.java
  src/main/java/com/pophory/pophoryserver/domain/photo/service/PhotoShareService.java
  src/main/java/com/pophory/pophoryserver/domain/pophorysm/PophorysmController.java
  src/main/java/com/pophory/pophoryserver/domain/pophorysm/PophorysmService.java
  src/main/java/com/pophory/pophoryserver/domain/pophorysm/dto/request/PophorysmShareRequestDto.java
  src/main/java/com/pophory/pophoryserver/domain/version/dto/response/PophorysmGetPresignedUrlResponseDto.java
Labels: 🚀API, 🐻UNAN

#150 [hotfix #149] 포포리즘 공유 API request body 수정
  .github/workflows/ci-prod.yml
  .github/workflows/ci.yml
  src/main/java/com/pophory/pophoryserver/domain/photo/controller/PhotoV2Controller.java
  src/main/java/com/pophory/pophoryserver/domain/pophorysm/PophorysmController.java
  src/main/java/com/pophory/pophoryserver/domain/pophorysm/dto/request/PophorysmShareRequestDto.java
  src/main/java/com/pophory/pophoryserver/global/entity/BaseTimeEntity.java
  src/main/resources/banner.txt
Labels: 🚀API, 🔥HOTFIX

#152 [fix #151] 배포 전 버그 수정 (access token 만료 시간 변경, 포포리즘 공유 API 수정)
  src/main/java/com/pophory/pophoryserver/domain/auth/SocialService.java
  src/main/java/com/pophory/pophoryserver/domain/pophorysm/PophorysmService.java
Labels: 🐞BUG, 🐻UNAN

#153 [fix #151] 포포리즘 공유시에 이미지 저장 url 변경
  src/main/java/com/pophory/pophoryserver/domain/pophorysm/PophorysmService.java
Labels: 🐞BUG

#157 [refactor #156] slack 회원가입시에 알람 추가
  .github/workflows/cd.yml
  scripts/deploy.sh
  src/main/java/com/pophory/pophoryserver/HealthCheckController.java
  src/main/java/com/pophory/pophoryserver/domain/member/MemberService.java
  src/main/java/com/pophory/pophoryserver/domain/member/controller/MemberV1Controller.java
  src/main/java/com/pophory/pophoryserver/domain/member/controller/MemberV2Controller.java
  src/main/java/com/pophory/pophoryserver/domain/slack/SlackService.java
  src/main/java/com/pophory/pophoryserver/domain/slack/dto/SlackMessageDto.java
Labels: 😉ENHANCEMENT, 🐻UNAN

#159 [fix #158] slack 메세지 알림 수정
  src/main/java/com/pophory/pophoryserver/domain/member/MemberService.java
  src/main/java/com/pophory/pophoryserver/domain/member/controller/MemberV1Controller.java
  src/main/java/com/pophory/pophoryserver/domain/member/controller/MemberV2Controller.java
  src/main/java/com/pophory/pophoryserver/domain/slack/SlackService.java
Labels: 🐞BUG, 🐻UNAN

#161 [deploy] 회원 가입 시에 slack 알람오는 기능 추가
  .github/workflows/cd.yml
  scripts/deploy.sh
  src/main/java/com/pophory/pophoryserver/HealthCheckController.java
  src/main/java/com/pophory/pophoryserver/domain/member/MemberService.java
  src/main/java/com/pophory/pophoryserver/domain/member/controller/MemberV1Controller.java
  src/main/java/com/pophory/pophoryserver/domain/member/controller/MemberV2Controller.java
  src/main/java/com/pophory/pophoryserver/domain/slack/SlackService.java
  src/main/java/com/pophory/pophoryserver/domain/slack/dto/SlackMessageDto.java
Labels: 🚀API, 🐻UNAN
